os: linux
dist: xenial
language: go
go:
    - 1.x
    - master
jobs:
    allow_failures:
        - go: master
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-lxc/lxc-git-master
    - sudo add-apt-repository -y ppa:projectatomic/ppa
    - sudo apt-get update
    - sudo apt-get install -yy lxc-utils lxc-dev libacl1-dev skopeo jq libcap-dev libgpgme11-dev
    - GO111MODULE=off go get github.com/openSUSE/umoci/cmd/umoci
    - sudo cp $GOPATH/bin/umoci /usr/bin
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
script:
    - env GO111MODULE=on make check
